language: go
sudo: false
go:
  - tip
git:
  depth: 5
install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/spf13/afero
script:
  - go test parser/* -v -covermode=count -coverprofile=profile.cov