language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/spf13/afero
script:
  - echo $GOPATH
  - ls $GOPATH/bin
  - ls $GOPATH/bin/goveralls
  - go test parser/* -v -covermode=count -coverprofile=profile.cov
  - ls ./
  - ls parser/
  # - goveralls -coverprofile=parser/profile.cov -service=travis-ci